name: Deploy Node_exporter Production

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Host to deploy'
        required: true
        default: 'production-infra'
        type: choice
        options:
          - production-frontend
          - production-backend
          - production-infra

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set deployment variables
        id: vars
        run: |
          if [[ "${{ github.event.inputs.host }}" == "production-frontend" ]]; then
            echo "VPS_HOST=${{ secrets.VPS_HOST_FRONT }}" >> $GITHUB_ENV
            echo "VPS_USERNAME=${{ secrets.VPS_USERNAME_FRONT }}" >> $GITHUB_ENV
            echo "VPS_SSH_KEY=${{ secrets.VPS_SSH_KEY_FRONT }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.host }}" == "production-backend" ]]; then
            echo "VPS_HOST=${{ secrets.VPS_HOST_BACK }}" >> $GITHUB_ENV
            echo "VPS_USERNAME=${{ secrets.VPS_USERNAME_BACK }}" >> $GITHUB_ENV
            echo "VPS_SSH_KEY=${{ secrets.VPS_SSH_KEY_BACK }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.host }}" == "production-infra" ]]; then
            echo "VPS_HOST=${{ secrets.VPS_HOST_INFRA }}" >> $GITHUB_ENV
            echo "VPS_USERNAME=${{ secrets.VPS_USERNAME_INFRA }}" >> $GITHUB_ENV
            echo "VPS_SSH_KEY=${{ secrets.VPS_SSH_KEY_INFRA }}" >> $GITHUB_ENV
          fi
          echo "VPS_PORT=${{ secrets.VPS_SSH_PORT_PROD }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Node_exporter
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          port: ${{ env.VPS_PORT }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ env.VPS_SSH_KEY }}
          script: |
            docker stop node_exporter || true
            docker rm node_exporter || true
            docker pull prom/node-exporter
            docker run -d --restart=unless-stopped --net="ngdem" --pid="host" \
              -v "/:/host:ro,rslave" \
              --name node_exporter \
              prom/node-exporter --path.rootfs=/host \
              --no-collector.arp

      - name: Verify Node_exporter
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          port: ${{ env.VPS_PORT }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ env.VPS_SSH_KEY }}
          script: |
            retries=5
            delay_seconds=10

            for attempt in $(seq "$retries"); do
              if docker ps --filter "name=node_exporter" --filter "status=running" | grep -q "node_exporter"; then
                echo "Node_exporter is running"
                exit 0
              else
                echo "Healthcheck failed (attempt $attempt/$retries)"
              fi

              if [ "$attempt" -lt "$retries" ]; then
                sleep "$delay_seconds"
              fi
            done

            echo "Node_exporter failed healthcheck after $retries attempts."
            exit 1
